#!/usr/bin/env python3
"""

Kullanım:
    pip install psycopg2-binary python-dotenv matplotlib numpy
    python performans_test.py
"""

import psycopg2
import psycopg2.extras
import random
import time
import os
import sys
import json
import shutil
import math
import subprocess
import tempfile
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from datetime import datetime, timedelta
from dotenv import load_dotenv
from pathlib import Path


load_dotenv()

DB_CONFIG = {
    'host':     os.getenv('PGHOST', ''),
    'port':     int(os.getenv('PGPORT',)),
    'user':     os.getenv('PGUSER', ''),
    'password': os.getenv('PGPASSWORD', ''),
    'database': os.getenv('PGDATABASE', ''),
}

# Artillery ile test edilecek sunucu adresi
ARTILLERY_TARGET = os.getenv('ARTILLERY_TARGET', 'http://localhost:3000')

SCRIPT_DIR  = Path(__file__).resolve().parent


PERFORMANS_DIR = SCRIPT_DIR.parent                # repo_root/Performans/
PERF_DATA_DIR  = PERFORMANS_DIR / 'data'          # repo_root/Performans/data/
OUTPUT_DIR     = PERFORMANS_DIR / 'sonuclar'      # repo_root/Performans/sonuclar/
PROJECT_DIR    = PERFORMANS_DIR.parent            # repo_root/
PHOTO_FILENAME  = '1763203444090_p2385k6hmk.jpg'
VIDEO_FILENAME  = '1763203444091_affw8078dnc.mp4'
PHOTO_SRC       = PERF_DATA_DIR / PHOTO_FILENAME
VIDEO_SRC       = PERF_DATA_DIR / VIDEO_FILENAME

UPLOADS_DIR = PROJECT_DIR / 'public' / 'uploads'

SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS public.users (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             text,
  password_hash        text,
  role                 text,
  name                 text,
  surname              text,
  email                text,
  email_verified       boolean DEFAULT false,
  is_verified          boolean DEFAULT false,
  verify_token         text,
  verify_expires       timestamptz,
  is_active            boolean DEFAULT true,
  deleted_by           text,
  deleted_by_role      text,
  deleted_by_id        integer,
  deleted_at           timestamptz,
  reset_code           text,
  reset_expires        timestamptz,
  two_factor_secret    text,
  two_factor_enabled   boolean DEFAULT false,
  two_factor_norm_hash text
);

CREATE TABLE IF NOT EXISTS public.olaylar (
  o_id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  o_adi                    text,
  active                   boolean DEFAULT true,
  created_by_name          text,
  created_by_role_name     text,
  created_by_id            integer,
  created_at               timestamptz DEFAULT now(),
  good                     boolean,
  deactivated_by_name      text,
  deactivated_by_role_name text,
  deactivated_by_id        integer,
  deactivated_at           timestamptz,
  is_point                 boolean DEFAULT true,
  is_line                  boolean DEFAULT false,
  is_polygon               boolean DEFAULT false,
  katman_tablo             text,
  attribute_column         text
);

CREATE TABLE IF NOT EXISTS public.olay (
  olay_id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enlem                    double precision,
  boylam                   double precision,
  olay_turu                integer REFERENCES public.olaylar(o_id)
                                   ON UPDATE CASCADE ON DELETE SET NULL,
  aciklama                 text,
  geom                     geometry(Point,4326),
  created_by_name          text,
  created_by_role_name     text,
  created_by_id            integer,
  active                   boolean DEFAULT true,
  deactivated_by_name      text,
  deactivated_by_role_name text,
  deactivated_by_id        integer,
  deactivated_at           timestamptz,
  created_at               timestamptz DEFAULT now(),
  photo_urls               text NOT NULL DEFAULT '[]',
  video_urls               text NOT NULL DEFAULT '[]'
);

CREATE INDEX IF NOT EXISTS users_username_idx     ON public.users (lower(btrim(username)));
CREATE INDEX IF NOT EXISTS users_email_idx        ON public.users (lower(btrim(email)));
CREATE INDEX IF NOT EXISTS idx_olay_created_by_id ON public.olay (created_by_id);
CREATE INDEX IF NOT EXISTS idx_olay_olay_turu     ON public.olay (olay_turu);
CREATE INDEX IF NOT EXISTS idx_olay_created_at    ON public.olay (created_at);
"""

PERF_TEST_PASSWORD = 'PerfTest1!'

# Ankara merkez bounding box: enlem 39.75–40.05, boylam 32.50–33.00
ANKARA_LAT_MIN = 39.75
ANKARA_LAT_MAX = 40.05
ANKARA_LNG_MIN = 32.50
ANKARA_LNG_MAX = 33.00


DOMAINS = ["k1.gov.tr", "k2.gov.tr", "k3.gov.tr", "k4.gov.tr", "k5.gov.tr",
           "k6.gov.tr", "k7.gov.tr", "k8.gov.tr", "k9.gov.tr", "k10.gov.tr"]

# Deney matrisi: kurum_sayisi × uzman_sayisi = 8 × 4 = 32 deney
KURUM_SAYILARI = list(range(3, 11))       # [3, 4, 5, 6, 7, 8, 9, 10]
UZMAN_SAYILARI = [10, 50, 100, 200]       # Her kuruma atanacak uzman sayısı

OLAY_TURLERI = [
    {'ad': 'Az Hasarlı',       'good': True},
    {'ad': 'Orta Hasarlı',     'good': True},
    {'ad': 'Çok Hasarlı',      'good': True},
    {'ad': 'Yıkık',            'good': True},
    {'ad': 'Elektrik kaçağı',  'good': False},
    {'ad': 'Su dağıtım',       'good': True},
    {'ad': 'Gaz kaçağı',       'good': False},
    {'ad': 'Polis',            'good': False},
    {'ad': 'Yemek dağıtım',   'good': True},
    {'ad': 'Erzak dağıtım',   'good': True},
    {'ad': 'Çocuk bakım',      'good': True},
]




def deney_matris_olustur():

    matris = []
    for k_sayisi in [KURUM_SAYILARI[-1]]:        # Tam: KURUM_SAYILARI  |  Az: [:1]
        for u_sayisi in [UZMAN_SAYILARI[-1]]:    # Tam: UZMAN_SAYILARI  |  Az: [:1]
            matris.append({
                'kurum_sayisi': k_sayisi,
                'uzman_sayisi': u_sayisi,
                'toplam_kullanici': k_sayisi * u_sayisi,
            })
    return matris



def get_coords():
    """Ankara il genelinde rastgele koordinat üret (bounding box)."""
    return (
        round(random.uniform(ANKARA_LAT_MIN, ANKARA_LAT_MAX), 6),
        round(random.uniform(ANKARA_LNG_MIN, ANKARA_LNG_MAX), 6),
    )

def get_date():
    return datetime.now() - timedelta(
        days=random.randint(0, 60),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59),
    )

def get_desc(olay_adi, good):
    if good:
        return f'{olay_adi} - Bölgede tespit edildi ve hizmet veriliyor'
    else:
        return f'{olay_adi} - Olay yerine ekipler sevk edildi'


# Veritabanı oluşturma / bağlanma
def admin_connect():
    """PostgreSQL sunucusuna 'postgres' bakım DB'si üzerinden bağlan."""
    try:
        conn = psycopg2.connect(
            host=DB_CONFIG['host'],
            port=DB_CONFIG['port'],
            user=DB_CONFIG['user'],
            password=DB_CONFIG['password'],
            database='postgres',
        )
        conn.autocommit = True
        return conn
    except Exception as e:
        print(f"[HATA] PostgreSQL sunucusuna bağlanılamadı: {e}")
        sys.exit(1)


def db_name_for(deney_no):
    return f"asis_deney_{deney_no}"


def create_experiment_db(admin_conn, deney_no):
    """Deney için yeni veritabanı oluştur (varsa sil yeniden oluştur)."""
    db_name = db_name_for(deney_no)
    cur = admin_conn.cursor()
    # Açık bağlantıları sonlandır
    cur.execute("""
        SELECT pg_terminate_backend(pid)
        FROM pg_stat_activity
        WHERE datname = %s AND pid <> pg_backend_pid()
    """, (db_name,))
    cur.execute(f'DROP DATABASE IF EXISTS "{db_name}"')
    cur.execute(f'CREATE DATABASE "{db_name}"')
    cur.close()
    return db_name


def connect_experiment_db(db_name):
    conn = psycopg2.connect(
        host=DB_CONFIG['host'],
        port=DB_CONFIG['port'],
        user=DB_CONFIG['user'],
        password=DB_CONFIG['password'],
        database=db_name,
    )
    conn.autocommit = False
    return conn


def setup_schema(conn):
    """Tablo yapısını ve eklentileri kur (1_veritabani_tablolari.sql uyumlu)."""
    conn.autocommit = True
    cur = conn.cursor()
    for statement in SCHEMA_SQL.split(';'):
        stmt = statement.strip()
        if stmt:
            try:
                cur.execute(stmt)
            except Exception:
                pass
    conn.autocommit = False


# Olay türleri, kullanıcılar, veri ekleme
def olay_turlerini_ekle(conn):
    cur = conn.cursor()
    olay_turu_ids = {}
    for ot in OLAY_TURLERI:
        cur.execute(
            "SELECT o_id FROM olaylar WHERE o_adi = %s AND COALESCE(active, true) = true",
            (ot['ad'],)
        )
        row = cur.fetchone()
        if row:
            olay_turu_ids[ot['ad']] = row[0]
        else:
            cur.execute(
                """INSERT INTO olaylar (o_adi, good, active, created_by_name, created_by_role_name)
                   VALUES (%s, %s, true, 'performans_test', 'admin')
                   RETURNING o_id""",
                (ot['ad'], ot['good'])
            )
            olay_turu_ids[ot['ad']] = cur.fetchone()[0]
    conn.commit()
    return olay_turu_ids


def kullanicilari_olustur(conn, deney_config):
    """Yeni veritabanında kullanıcıları oluştur.
    deney_config: {
        'kurum_sayisi': int,    # Kaç kurum seçilecek (3..10)
        'uzman_sayisi': int,    # Her kuruma kaç uzman (10, 50, 100, 200)
    }
    DOMAINS listesinden kurum_sayisi kadar rastgele seçilir,
    her seçilen domain'e uzman_sayisi kadar kullanıcı eklenir.
    """
    cur = conn.cursor()
    kurum_sayisi = deney_config['kurum_sayisi']
    uzman_sayisi = deney_config['uzman_sayisi']

    # Düz listeden rastgele domain seç
    secilen_domainler = random.sample(DOMAINS, kurum_sayisi)

    kullanici_idleri = []
    kurum_kullanici_map = {}

    for domain in secilen_domainler:
        kisaltma = domain.split('.')[0]  # "k1.gov.tr" → "k1"
        kurum_ids = []
        for u_idx in range(uzman_sayisi):
            username = f"{kisaltma}_{u_idx+1}"
            email = f"{username}@{domain}"

            cur.execute(
                """INSERT INTO users (
                       username, password_hash, role, email,
                       email_verified, is_verified, is_active
                   ) VALUES (
                       %s,
                       crypt(%s, gen_salt('bf', 4)),
                       'user', %s,
                       true, true, true
                   )
                   RETURNING id""",
                (username, PERF_TEST_PASSWORD, email)
            )
            uid = cur.fetchone()[0]

            kullanici_idleri.append({
                'id': uid,
                'username': username,
                'kurum': domain,
                'domain': domain,
            })
            kurum_ids.append(uid)

        kurum_kullanici_map[domain] = kurum_ids

    conn.commit()
    return kullanici_idleri, kurum_kullanici_map


def veri_ekle(conn, kullanicilar, olay_turu_ids):
    cur = conn.cursor()
    olay_adi_listesi = list(olay_turu_ids.keys())
    olay_id_listesi = list(olay_turu_ids.values())

    toplam_eklenen = 0
    insert_suresi_baslangic = time.time()
    batch_data = []

    for user_info in kullanicilar:
        veri_sayisi = random.randint(10, 50)
        for _ in range(veri_sayisi):
            lat, lng = get_coords()
            tarih = get_date()
            olay_idx = random.randint(0, len(olay_adi_listesi) - 1)
            olay_adi = olay_adi_listesi[olay_idx]
            olay_id  = olay_id_listesi[olay_idx]
            olay_good = OLAY_TURLERI[olay_idx]['good']
            aciklama = get_desc(olay_adi, olay_good)

            has_photo = random.random() < 0.5
            has_video = random.random() < 0.5
            photo_urls = json.dumps([f'/uploads/{PHOTO_FILENAME}']) if has_photo else '[]'
            video_urls = json.dumps([f'/uploads/{VIDEO_FILENAME}']) if has_video else '[]'

            batch_data.append((
                lat, lng, olay_id, aciklama, lng, lat,
                user_info['username'], 'user', user_info['id'],
                photo_urls, video_urls, tarih
            ))
            toplam_eklenen += 1

    insert_sql = """
        INSERT INTO olay (
            enlem, boylam, olay_turu, aciklama, geom,
            created_by_name, created_by_role_name, created_by_id,
            photo_urls, video_urls, created_at, active
        ) VALUES %s
    """
    template = """(
        %s, %s, %s, %s, ST_SetSRID(ST_MakePoint(%s, %s), 4326),
        %s, %s, %s, %s, %s, %s, true
    )"""

    BATCH_SIZE = 5000
    for i in range(0, len(batch_data), BATCH_SIZE):
        chunk = batch_data[i:i + BATCH_SIZE]
        psycopg2.extras.execute_values(
            cur, insert_sql, chunk, template=template, page_size=BATCH_SIZE
        )

    conn.commit()
    insert_suresi = time.time() - insert_suresi_baslangic
    return toplam_eklenen, insert_suresi


# ════════════════════════════════════════════════════════════════
#  Artillery HTTP Yük Testi
# ════════════════════════════════════════════════════════════════

def artillery_csv_olustur(kullanicilar, csv_path):
    """Artillery için test kullanıcıları CSV dosyasını oluştur."""
    lines = ['username,password']
    for u in kullanicilar:
        lines.append(f"{u['username']},{PERF_TEST_PASSWORD}")
    with open(csv_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def artillery_yaml_olustur(kullanici_sayisi, csv_path, yaml_path, helpers_path):
    """Kullanıcı sayısına göre dinamik Artillery YAML konfigürasyonu oluştur.

    arrivalRate: Saniyede oluşturulacak sanal kullanıcı sayısı
    duration:    Testin toplam süresi (saniye)

    Kullanıcı sayısı arttıkça arrivalRate ve duration ölçeklenir.
    """
    # Windows ters-slash'larını forward-slash'a çevir (Node.js/YAML uyumluluğu)
    csv_path_safe = str(csv_path).replace('\\', '/')
    helpers_path_safe = str(helpers_path).replace('\\', '/')

    # arrivalRate'i kullanıcı sayısına göre ölçekle
    if kullanici_sayisi <= 50:
        arrival_rate = 5
        duration = 10
    elif kullanici_sayisi <= 200:
        arrival_rate = 15
        duration = 15
    elif kullanici_sayisi <= 500:
        arrival_rate = 30
        duration = 20
    elif kullanici_sayisi <= 1000:
        arrival_rate = 50
        duration = 25
    else:
        arrival_rate = 80
        duration = 30

    yaml_content = f"""config:
  target: "{ARTILLERY_TARGET}"
  phases:
    - duration: {duration}
      arrivalRate: {arrival_rate}
      name: "Yük Testi ({kullanici_sayisi} kullanıcı)"
  defaults:
    headers:
      Content-Type: "application/json"
  processor: "{helpers_path_safe}"
  payload:
    path: "{csv_path_safe}"
    fields:
      - "username"
      - "password"
    order: "random"
    skipHeader: true

scenarios:
  - name: "Giriş + Olay Listeleme"
    weight: 40
    flow:
      - post:
          url: "/api/auth/login"
          json:
            usernameOrEmail: "{{{{ username }}}}"
            password: "{{{{ password }}}}"
          capture:
            - json: "$.token"
              as: "authToken"
      - get:
          url: "/api/olaylar_tum"
          headers:
            Authorization: "Bearer {{{{ authToken }}}}"
      - get:
          url: "/api/olaylar"
          headers:
            Authorization: "Bearer {{{{ authToken }}}}"

  - name: "Giriş + Olay Ekleme"
    weight: 30
    flow:
      - post:
          url: "/api/auth/login"
          json:
            usernameOrEmail: "{{{{ username }}}}"
            password: "{{{{ password }}}}"
          capture:
            - json: "$.token"
              as: "authToken"
      - function: "generateRandomEvent"
      - post:
          url: "/api/submit_olay"
          headers:
            Authorization: "Bearer {{{{ authToken }}}}"
          json:
            enlem: "{{{{ randomLat }}}}"
            boylam: "{{{{ randomLng }}}}"
            olay_turu: "{{{{ randomOlayTuru }}}}"
            aciklama: "{{{{ randomAciklama }}}}"
            photo_urls: []
            video_urls: []

  - name: "Medyalı Olay"
    weight: 15
    flow:
      - post:
          url: "/api/auth/login"
          json:
            usernameOrEmail: "{{{{ username }}}}"
            password: "{{{{ password }}}}"
          capture:
            - json: "$.token"
              as: "authToken"
      - function: "generateRandomEvent"
      - post:
          url: "/api/submit_olay"
          headers:
            Authorization: "Bearer {{{{ authToken }}}}"
          json:
            enlem: "{{{{ randomLat }}}}"
            boylam: "{{{{ randomLng }}}}"
            olay_turu: "{{{{ randomOlayTuru }}}}"
            aciklama: "Medyalı test olay bildirimi"
            photo_urls:
              - "/uploads/{PHOTO_FILENAME}"
            video_urls:
              - "/uploads/{VIDEO_FILENAME}"

  - name: "Sağlık Kontrolü"
    weight: 15
    flow:
      - get:
          url: "/health"
      - get:
          url: "/api/config"
      - think: 1
"""
    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)


def artillery_binary_bul():
    """Artillery binary yolunu bul. Önce lokal node_modules, sonra global aranır.

    Windows'ta node_modules/.bin/artillery bir bash script'tir ve çalışmaz.
    Windows'ta .cmd uzantılı dosya kullanılmalıdır.

    Returns:
        str veya None: Artillery çalıştırılabilir dosyanın tam yolu
    """
    is_windows = sys.platform.startswith('win')

    # 1) Lokal: node_modules/.bin/ içinde ara
    bin_dir = SCRIPT_DIR / 'node_modules' / '.bin'
    if is_windows:
        # Windows: artillery.cmd kullan 
        lokal_cmd = bin_dir / 'artillery.cmd'
        if lokal_cmd.exists():
            return str(lokal_cmd)
    else:
        # Linux/macOS: artillery (bash script)
        lokal_bin = bin_dir / 'artillery'
        if lokal_bin.exists():
            return str(lokal_bin)

    # 2) Global kurulum: shutil.which ile platformdan bağımsız ara
    global_path = shutil.which('artillery')
    if global_path:
        return global_path

    return None


def artillery_kur():
    """Artillery'yi Performans/artillery/ dizininde npm install ile kur.

    Returns:
        bool: Kurulum başarılı mı
    """
    pkg_json = SCRIPT_DIR / 'package.json'
    if not pkg_json.exists():
        print(f"  [HATA] package.json bulunamadı: {pkg_json}")
        return False

    # package.json içinde artillery var mı kontrol et
    with open(pkg_json, 'r', encoding='utf-8') as f:
        pkg = json.load(f)
    deps = pkg.get('dependencies', {})
    if 'artillery' not in deps:
        print(f"  [HATA] package.json içinde 'artillery' bağımlılığı yok!")
        print(f"         Lütfen package.json dosyasına ekleyin:")
        print(f'         "artillery": "^2.0.22"')
        return False

    print(f"  [NPM] Artillery kuruluyor: npm install --prefix {SCRIPT_DIR} ...")
    is_windows = sys.platform.startswith('win')
    try:
        result = subprocess.run(
            ['npm', 'install'],
            capture_output=True, text=True, timeout=120,
            cwd=str(SCRIPT_DIR),
            shell=is_windows  # Windows'ta npm.cmd için shell gerekir
        )
        if result.returncode != 0:
            print(f"  [HATA] npm install başarısız:")
            print(f"         {result.stderr[:500]}")
            return False

        print(f"  [OK] Artillery başarıyla kuruldu.")
        return True
    except FileNotFoundError:
        print(f"  [HATA] 'npm' komutu bulunamadı. Node.js kurulu mu?")
        print(f"         Kurulum: https://nodejs.org/")
        return False
    except subprocess.TimeoutExpired:
        print(f"  [HATA] npm install zaman aşımına uğradı (120s).")
        return False


def artillery_calistir(yaml_path, json_output_path):
    """Artillery testini çalıştır ve JSON raporunu döndür.

    Akış:
      1. Artillery binary aranır (lokal node_modules → global)
      2. Bulunamazsa npm install ile otomatik kurulur
      3. Kurulum da başarısızsa None döner (test atlanır)

    Returns:
        dict veya None: Artillery sonuç metrikleri
            - toplam_istek: Toplam HTTP istek sayısı
            - basarili_istek: Başarılı istek sayısı (2xx)
            - ortalama_yanit_ms: Ortalama yanıt süresi (ms)
            - p95_yanit_ms: p95 yanıt süresi (ms)
            - p99_yanit_ms: p99 yanıt süresi (ms)
            - istek_saniye: Saniyedeki istek sayısı (throughput)
            - hata_sayisi: Hata sayısı
    """
    # ── 1) Artillery binary'sini bul ──
    artillery_bin = artillery_binary_bul()

    # ── 2) Bulunamazsa otomatik kur ──
    if artillery_bin is None:
        print(f"  [BİLGİ] Artillery bulunamadı, otomatik kurulum deneniyor...")
        if artillery_kur():
            artillery_bin = artillery_binary_bul()
        if artillery_bin is None:
            print(f"  [UYARI] Artillery kurulamadı, HTTP testi atlanıyor.")
            return None

    # ── 3) Artillery'yi çalıştır ──
    is_windows = sys.platform.startswith('win')
    try:
        cmd = [artillery_bin, 'run', '--output', str(json_output_path), str(yaml_path)]
        result = subprocess.run(
            cmd,
            capture_output=True, text=True, timeout=300,
            cwd=str(SCRIPT_DIR),
            shell=is_windows  # Windows'ta .cmd dosyaları shell gerektirir
        )

        if result.returncode != 0:
            stderr_short = result.stderr[:300] if result.stderr else ''
            print(f"  [UYARI] Artillery çalıştırma hatası (exit={result.returncode}): {stderr_short}")
            return None

        if not Path(json_output_path).exists():
            print(f"  [UYARI] Artillery JSON raporu oluşmadı.")
            return None

        with open(json_output_path, 'r', encoding='utf-8') as f:
            rapor = json.load(f)

        # Artillery JSON yapısından metrikleri çıkar
        aggregate = rapor.get('aggregate', {})
        counters = aggregate.get('counters', {})
        summaries = aggregate.get('summaries', {})

        http_response_time = summaries.get('http.response_time', {})

        toplam_istek = counters.get('http.requests', 0)

        basarili_2xx = 0
        hatali_4xx = 0
        hatali_5xx = 0
        kod_dagilimi = {}

        for key, val in counters.items():
            if key.startswith('http.codes.'):
                kod = int(key.split('.')[-1])
                kod_dagilimi[kod] = val
                if 200 <= kod < 300:
                    basarili_2xx += val
                elif 400 <= kod < 500:
                    hatali_4xx += val
                elif 500 <= kod < 600:
                    hatali_5xx += val

        basarisiz = toplam_istek - basarili_2xx

        # Yanıt süresi — tüm yüzdelikler
        http_rt = summaries.get('http.response_time', {})

        return {
            'toplam_istek': toplam_istek,
            'basarili_2xx': basarili_2xx,
            'basarisiz': basarisiz,
            'hatali_4xx': hatali_4xx,
            'hatali_5xx': hatali_5xx,
            'kod_dagilimi': kod_dagilimi,
            'yanit_min_ms': http_rt.get('min', 0),
            'yanit_max_ms': http_rt.get('max', 0),
            'yanit_ortalama_ms': round(http_rt.get('mean', 0), 2),
            'yanit_medyan_ms': http_rt.get('median', 0),
            'yanit_p95_ms': http_rt.get('p95', 0),
            'yanit_p99_ms': http_rt.get('p99', 0),
            'istek_saniye': aggregate.get('rates', {}).get('http.request_rate', 0),
            'vusers_olusturulan': counters.get('vusers.created', 0),
            'vusers_tamamlanan': counters.get('vusers.completed', 0),
            'vusers_basarisiz': counters.get('vusers.failed', 0),
        }

    except subprocess.TimeoutExpired:
        print(f"  [UYARI] Artillery zaman aşımına uğradı (300s).")
        return None
    except Exception as e:
        print(f"  [UYARI] Artillery hatası: {e}")
        return None


# ════════════════════════════════════════════════════════════════
#  Sorgular (6 adet)
# ════════════════════════════════════════════════════════════════

def sorgu_calistir(conn, sql, params=None):
    cur = conn.cursor()
    baslangic = time.time()
    cur.execute(sql, params or ())
    rows = cur.fetchall()
    sure = time.time() - baslangic
    return rows, sure


def supervizor_sorgulari(conn, kurum_kullanici_map):
    sonuclar = {}
    domain_list = list(kurum_kullanici_map.keys())
    secili_domain = random.choice(domain_list)
    secili_kurum = secili_domain  # DOMAINS düz liste, domain'in kendisi isim

    tum_userids = []
    for ids in kurum_kullanici_map.values():
        tum_userids.extend(ids)
    secili_user_id = random.choice(tum_userids) if tum_userids else 1

    cur = conn.cursor()
    cur.execute("SELECT o_id FROM olaylar WHERE COALESCE(active,true)=true ORDER BY random() LIMIT 1")
    secili_olay_turu = cur.fetchone()[0]

    t2 = datetime.now()
    t1 = t2 - timedelta(days=30)

    # ── Sorgu 1: Kurum Sorgulama ──
    sql1 = """
        SELECT o.olay_id, o.enlem, o.boylam, o.olay_turu, o.aciklama,
               o.created_by_name, o.photo_urls, o.video_urls, o.created_at
        FROM olay o JOIN users u ON o.created_by_id = u.id
        WHERE u.email LIKE %s AND COALESCE(o.active, true) = true
    """
    rows1, sure1 = sorgu_calistir(conn, sql1, (f'%@{secili_domain}',))
    sonuclar['sorgu1_kurum'] = {'ad': f'Kurum ({secili_kurum})', 'sure_sn': round(sure1, 4), 'sonuc_sayisi': len(rows1)}

    # ── Sorgu 2: Uzman Sorgulama ──
    sql2 = """
        SELECT o.olay_id, o.enlem, o.boylam, o.olay_turu, o.aciklama,
               o.created_by_name, o.photo_urls, o.video_urls, o.created_at
        FROM olay o WHERE o.created_by_id = %s AND COALESCE(o.active, true) = true
    """
    rows2, sure2 = sorgu_calistir(conn, sql2, (secili_user_id,))
    sonuclar['sorgu2_uzman'] = {'ad': f'Uzman (id={secili_user_id})', 'sure_sn': round(sure2, 4), 'sonuc_sayisi': len(rows2)}

    # ── Sorgu 3: Olay Türü Sorgulama ──
    sql3 = """
        SELECT o.olay_id, o.enlem, o.boylam, o.aciklama,
               o.created_by_name, o.photo_urls, o.video_urls, o.created_at
        FROM olay o WHERE o.olay_turu = %s AND COALESCE(o.active, true) = true
    """
    rows3, sure3 = sorgu_calistir(conn, sql3, (secili_olay_turu,))
    sonuclar['sorgu3_olay_turu'] = {'ad': f'Olay türü (id={secili_olay_turu})', 'sure_sn': round(sure3, 4), 'sonuc_sayisi': len(rows3)}

    # ── Sorgu 4: Medyalı Olay Sorgulama ──
    sql4 = """
        SELECT o.olay_id, o.enlem, o.boylam, o.aciklama,
               o.created_by_name, o.photo_urls, o.video_urls, o.created_at
        FROM olay o
        WHERE o.olay_turu = %s AND COALESCE(o.active, true) = true
          AND ((o.photo_urls IS NOT NULL AND o.photo_urls <> '[]')
               OR (o.video_urls IS NOT NULL AND o.video_urls <> '[]'))
    """
    rows4, sure4 = sorgu_calistir(conn, sql4, (secili_olay_turu,))
    sonuclar['sorgu4_medya'] = {'ad': f'Medyalı (tür={secili_olay_turu})', 'sure_sn': round(sure4, 4), 'sonuc_sayisi': len(rows4)}

    # ── Sorgu 5: Tarih aralığı + Kurum Sorgulama ──
    sql5 = """
        SELECT o.olay_id, o.enlem, o.boylam, o.olay_turu, o.aciklama,
               o.created_by_name, o.photo_urls, o.video_urls, o.created_at
        FROM olay o JOIN users u ON o.created_by_id = u.id
        WHERE u.email LIKE %s AND o.created_at BETWEEN %s AND %s
          AND COALESCE(o.active, true) = true
    """
    rows5, sure5 = sorgu_calistir(conn, sql5, (f'%@{secili_domain}', t1, t2))
    sonuclar['sorgu5_tarih_kurum'] = {'ad': f'Tarih aralığı+Kurum ({secili_kurum})', 'sure_sn': round(sure5, 4), 'sonuc_sayisi': len(rows5)}

    # ── Sorgu 6: T1-T2 tarih aralığında [X] kurumundan toplanan veri (COUNT) ──
    sql6 = """
        SELECT COUNT(*) AS toplanan_veri
        FROM olay o JOIN users u ON o.created_by_id = u.id
        WHERE u.email LIKE %s AND o.created_at BETWEEN %s AND %s
          AND COALESCE(o.active, true) = true
    """
    rows6, sure6 = sorgu_calistir(conn, sql6, (f'%@{secili_domain}', t1, t2))
    toplanan_veri = rows6[0][0] if rows6 else 0
    sonuclar['sorgu6_tarih_kurum_count'] = {
        'ad': f'T1-T2 {secili_kurum} toplanan veri',
        'sure_sn': round(sure6, 4),
        'sonuc_sayisi': toplanan_veri
    }

    return sonuclar


# ════════════════════════════════════════════════════════════════
#  SVG Grafik ve Tablo Oluşturma
# ════════════════════════════════════════════════════════════════

def stil_uygula(ax, xlabel='', ylabel='', title='', fontsize_label=14, fontsize_title=15):
    """Tüm grafiklere ortak stil uygula:
    - Sadece sol (y) ve alt (x) eksenler görünsün, kalın olsun
    - Eksen etiketleri büyük puntolu
    - Y ekseni eşit aralıklı (MaxNLocator)
    """
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_linewidth(2.5)
    ax.spines['bottom'].set_linewidth(2.5)
    ax.tick_params(axis='both', width=2, length=6, labelsize=12)
    # Y ekseni eşit aralıklı tick'ler
    ax.yaxis.set_major_locator(ticker.MaxNLocator(nbins=8, integer=False))
    if xlabel:
        ax.set_xlabel(xlabel, fontsize=fontsize_label, fontweight='bold')
    if ylabel:
        ax.set_ylabel(ylabel, fontsize=fontsize_label, fontweight='bold')
    if title:
        ax.set_title(title, fontsize=fontsize_title, fontweight='bold')
    ax.grid(True, alpha=0.3, linewidth=0.5)


def grafik_olustur(tum_sonuclar, output_dir):
    output_dir.mkdir(parents=True, exist_ok=True)

    deney_nolari       = [s['deney_no'] for s in tum_sonuclar]
    kullanici_sayilari = [s['kullanici_sayisi'] for s in tum_sonuclar]
    toplam_veriler     = [s['toplam_veri'] for s in tum_sonuclar]
    insert_sureleri    = [s['insert_suresi'] for s in tum_sonuclar]

    # ── 6 sorgu tanımı (eski 5 + yeni 6. sorgu) ──
    sorgu_isimleri = [
        ('sorgu1_kurum',             'S1: Kurum Sorgulama'),
        ('sorgu2_uzman',             'S2: Uzman Sorgulama'),
        ('sorgu3_olay_turu',         'S3: Olay Türü Sorgulama'),
        ('sorgu4_medya',             'S4: Medyalı Olay Sorgulama'),
        ('sorgu5_tarih_kurum',       'S5: Tarih aralığı + Kurum Sorgulama'),
        ('sorgu6_tarih_kurum_count', 'S6: T1-T2 Tarih Aralığında Kurumdan Toplanan Veri'),
    ]
    sorgu_sureleri = {}
    for key, label in sorgu_isimleri:
        sorgu_sureleri[key] = [s['sorgular'][key]['sure_sn'] for s in tum_sonuclar]

    plt.rcParams.update({'font.size': 12, 'figure.dpi': 150, 'axes.grid': True, 'grid.alpha': 0.3})
    renk_paleti = ['#E91E63', '#FF9800', '#9C27B0', '#00BCD4', '#8BC34A', '#FF5722']

    # ── 1: Insert Süresi ──
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(range(len(kullanici_sayilari)), insert_sureleri, 'o-', color='#2196F3', linewidth=2, markersize=5)
    stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='Süre (saniye)',
                title='Kullanıcı Sayısına Göre Veri Ekleme Süresi')
    # Eşit aralıklı tick'ler: veri indekslerinden eşit adımlarla seç
    n_ticks = min(10, len(kullanici_sayilari))
    tick_idx = np.linspace(0, len(kullanici_sayilari) - 1, n_ticks, dtype=int)
    ax.set_xticks(tick_idx)
    ax.set_xticklabels([f'{kullanici_sayilari[i]:,}' for i in tick_idx], rotation=45, ha='right')
    fig.tight_layout()
    fig.savefig(output_dir / '01_insert_suresi.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 01_insert_suresi.svg")

    # ── 2: Toplam Veri ──
    fig, ax = plt.subplots(figsize=(12, 6))
    # Eşit aralıklı bar grafiği
    x_pos = np.arange(len(deney_nolari))
    ax.bar(x_pos, toplam_veriler, color='#4CAF50', alpha=0.8)
    stil_uygula(ax, xlabel='Deney No', ylabel='Toplam Veri Sayısı',
                title='Her Deneydeki Toplam Veri Miktarı')
    # Eşit aralıklı tick'ler
    tick_step = max(1, len(deney_nolari) // 8)
    tick_positions = list(range(0, len(deney_nolari), tick_step))
    ax.set_xticks(tick_positions)
    ax.set_xticklabels([str(deney_nolari[i]) for i in tick_positions])
    fig.tight_layout(); fig.savefig(output_dir / '02_toplam_veri.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 02_toplam_veri.svg")

    # ── 3: Sorgu Süreleri (6 sorgu) ──
    fig, ax = plt.subplots(figsize=(14, 7))
    x_idx = range(len(kullanici_sayilari))
    for idx, (key, label) in enumerate(sorgu_isimleri):
        ax.plot(x_idx, sorgu_sureleri[key], 'o-',
                color=renk_paleti[idx], linewidth=2, markersize=4, label=label)
    stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='Sorgu Süresi (s)',
                title='Süpervizör Sorgu Süreleri vs Kullanıcı Sayısı')
    ax.legend(fontsize=10, loc='upper left')
    n_ticks = min(10, len(kullanici_sayilari))
    tick_idx = np.linspace(0, len(kullanici_sayilari) - 1, n_ticks, dtype=int)
    ax.set_xticks(tick_idx)
    ax.set_xticklabels([f'{kullanici_sayilari[i]:,}' for i in tick_idx], rotation=45, ha='right')
    fig.tight_layout(); fig.savefig(output_dir / '03_sorgu_sureleri.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 03_sorgu_sureleri.svg")

    # ── 4: Ortalama Yanıt Süreleri (6 sorgu) ──
    fig, ax = plt.subplots(figsize=(12, 7))
    ort_sureler = [np.mean(sorgu_sureleri[k]) for k, _ in sorgu_isimleri]
    std_sureler = [np.std(sorgu_sureleri[k]) for k, _ in sorgu_isimleri]
    # Eşit aralıklı bar pozisyonları
    x_pos = np.arange(len(sorgu_isimleri))
    bars = ax.bar(x_pos, ort_sureler, yerr=std_sureler, capsize=5,
                  color=renk_paleti, alpha=0.85, edgecolor='black', linewidth=0.5)
    stil_uygula(ax, ylabel='Ortalama Süre (s)', title='Ortalama Yanıt Süreleri')
    ax.set_xticks(x_pos)
    ax.set_xticklabels([l for _, l in sorgu_isimleri], rotation=25, ha='right', fontsize=10)
    for bar, val in zip(bars, ort_sureler):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.001,
                f'{val:.4f}s', ha='center', va='bottom', fontsize=9, fontweight='bold')
    fig.tight_layout(); fig.savefig(output_dir / '04_ortalama_sorgu_sureleri.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 04_ortalama_sorgu_sureleri.svg")

    # ── 5: Insert Hızı ──
    fig, ax = plt.subplots(figsize=(12, 6))
    hizlar = [v / max(s, 0.001) for v, s in zip(toplam_veriler, insert_sureleri)]
    ax.plot(range(len(kullanici_sayilari)), hizlar, 's-', color='#FF5722', linewidth=2, markersize=5)
    stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='Veri/Saniye',
                title='Veri Ekleme Hızı (throughput)')
    n_ticks = min(10, len(kullanici_sayilari))
    tick_idx = np.linspace(0, len(kullanici_sayilari) - 1, n_ticks, dtype=int)
    ax.set_xticks(tick_idx)
    ax.set_xticklabels([f'{kullanici_sayilari[i]:,}' for i in tick_idx], rotation=45, ha='right')
    fig.tight_layout(); fig.savefig(output_dir / '05_insert_hizi.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 05_insert_hizi.svg")

    # ── 6: Isı Haritası (6 sorgu) ──
    fig, ax = plt.subplots(figsize=(14, 7))
    matrix = [[s['sorgular'][k]['sonuc_sayisi'] for s in tum_sonuclar] for k, _ in sorgu_isimleri]
    im = ax.imshow(matrix, aspect='auto', cmap='YlOrRd')
    ax.set_yticks(range(len(sorgu_isimleri)))
    ax.set_yticklabels([l for _, l in sorgu_isimleri], fontsize=10)
    # Eşit aralıklı x tick'leri
    tick_step = max(1, len(deney_nolari) // 8)
    xtick_pos = list(range(0, len(deney_nolari), tick_step))
    ax.set_xticks(xtick_pos)
    ax.set_xticklabels([str(deney_nolari[i]) for i in xtick_pos])
    stil_uygula(ax, xlabel='Deney No', title='Sorgu Sonuç Sayıları (Isı Haritası)')
    fig.colorbar(im, label='Sonuç Sayısı')
    fig.tight_layout(); fig.savefig(output_dir / '06_sorgu_sonuc_isi_haritasi.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 06_sorgu_sonuc_isi_haritasi.svg")

    # ── 7: Özet Tablosu (6 sorgu) ──
    fig, ax = plt.subplots(figsize=(24, max(10, len(tum_sonuclar)*0.35+2)))
    ax.axis('off')
    ax.set_title('Deney Sonuçları Özet Tablosu', fontsize=16, fontweight='bold', pad=20)
    basliklar = ['Deney\nNo','DB Adı','Kurum\nSayısı','Uzman\nSayısı','Toplam\nKullanıcı','Toplam\nVeri','Insert\nSüresi(s)',
                 'S1\nKurum(s)','S2\nUzman(s)','S3\nOlay(s)','S4\nMedya(s)',
                 'S5\nTarih+\nKurum(s)','S6\nToplanan\nVeri(s)']
    rows = []
    for s in tum_sonuclar:
        rows.append([
            str(s['deney_no']), s['db_adi'],
            str(s.get('kurum_sayisi', '')), str(s.get('uzman_sayisi', '')),
            f"{s['kullanici_sayisi']:,}", f"{s['toplam_veri']:,}",
            f"{s['insert_suresi']:.3f}",
            f"{s['sorgular']['sorgu1_kurum']['sure_sn']:.4f}",
            f"{s['sorgular']['sorgu2_uzman']['sure_sn']:.4f}",
            f"{s['sorgular']['sorgu3_olay_turu']['sure_sn']:.4f}",
            f"{s['sorgular']['sorgu4_medya']['sure_sn']:.4f}",
            f"{s['sorgular']['sorgu5_tarih_kurum']['sure_sn']:.4f}",
            f"{s['sorgular']['sorgu6_tarih_kurum_count']['sure_sn']:.4f}",
        ])
    tablo = ax.table(cellText=rows, colLabels=basliklar, loc='center', cellLoc='center')
    tablo.auto_set_font_size(False); tablo.set_fontsize(7); tablo.scale(1, 1.4)
    for j in range(len(basliklar)):
        tablo[0,j].set_facecolor('#1976D2'); tablo[0,j].set_text_props(color='white', fontweight='bold')
    for i in range(1, len(rows)+1):
        for j in range(len(basliklar)):
            tablo[i,j].set_facecolor('#E3F2FD' if i%2==0 else '#FFFFFF')
    fig.tight_layout()
    fig.savefig(output_dir / '07_ozet_tablosu.svg', format='svg', bbox_inches='tight'); plt.close(fig)
    print(f"  [SVG] 07_ozet_tablosu.svg")

    # ── 8: İstatistik Özeti (6 sorgu) ──
    fig, ax = plt.subplots(figsize=(14, 7))
    ax.axis('off')
    ax.set_title('İstatistiksel Özet', fontsize=16, fontweight='bold', pad=20)
    ist_baslik = ['Metrik','Min','Max','Ortalama','Medyan','Std Sapma']
    metrikler = [
        ('Kullanıcı Sayısı',                   kullanici_sayilari),
        ('Toplam Veri',                         toplam_veriler),
        ('Insert Süresi (s)',                   insert_sureleri),
        ('S1: Kurum (s)',                       sorgu_sureleri['sorgu1_kurum']),
        ('S2: Uzman (s)',                       sorgu_sureleri['sorgu2_uzman']),
        ('S3: Olay Türü (s)',                   sorgu_sureleri['sorgu3_olay_turu']),
        ('S4: Medya (s)',                       sorgu_sureleri['sorgu4_medya']),
        ('S5: Tarih aralığı+Kurum (s)',         sorgu_sureleri['sorgu5_tarih_kurum']),
        ('S6: Toplanan Veri (s)',               sorgu_sureleri['sorgu6_tarih_kurum_count']),
    ]
    ist_rows = []
    for ad, v in metrikler:
        a = np.array(v)
        ist_rows.append([ad, f"{a.min():.4f}", f"{a.max():.4f}",
                         f"{a.mean():.4f}", f"{np.median(a):.4f}", f"{a.std():.4f}"])
    t2 = ax.table(cellText=ist_rows, colLabels=ist_baslik, loc='center', cellLoc='center')
    t2.auto_set_font_size(False); t2.set_fontsize(9); t2.scale(1, 1.6)
    for j in range(len(ist_baslik)):
        t2[0,j].set_facecolor('#388E3C'); t2[0,j].set_text_props(color='white', fontweight='bold')
    for i in range(1, len(ist_rows)+1):
        for j in range(len(ist_baslik)):
            t2[i,j].set_facecolor('#E8F5E9' if i%2==0 else '#FFFFFF')
    fig.tight_layout()
    fig.savefig(output_dir / '08_istatistik_ozeti.svg', format='svg', bbox_inches='tight'); plt.close(fig)
    print(f"  [SVG] 08_istatistik_ozeti.svg")

    # ── 9: Box Plot (6 sorgu) ──
    fig, ax = plt.subplots(figsize=(14, 7))
    bp = ax.boxplot([sorgu_sureleri[k] for k, _ in sorgu_isimleri],
                    patch_artist=True,
                    labels=[l for _, l in sorgu_isimleri])
    for patch, color in zip(bp['boxes'], renk_paleti):
        patch.set_facecolor(color)
        patch.set_alpha(0.6)
    stil_uygula(ax, ylabel='Sorgu Süresi (s)', title='Sorgu Süresi Dağılımları (Box Plot)')
    ax.set_xticklabels([l for _, l in sorgu_isimleri], rotation=20, ha='right', fontsize=10)
    fig.tight_layout(); fig.savefig(output_dir / '09_sorgu_boxplot.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 09_sorgu_boxplot.svg")

    # ── 10: Scatter – Tüm noktalar SİYAH (6 sorgu → 2x3 grid) ──
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    axes_flat = axes.flatten()
    for idx, (key, label) in enumerate(sorgu_isimleri):
        ax = axes_flat[idx]
        # ★ Tüm noktalar siyah, tek renk, içi dolu
        ax.scatter(toplam_veriler, sorgu_sureleri[key],
                   c='black', s=30, alpha=0.8,
                   edgecolor='black', linewidth=0.3)
        z = np.polyfit(toplam_veriler, sorgu_sureleri[key], 1)
        p = np.poly1d(z)
        x_fit = np.linspace(min(toplam_veriler), max(toplam_veriler), 100)
        ax.plot(x_fit, p(x_fit), '--', color='gray', alpha=0.7)
        stil_uygula(ax, xlabel='Toplam Veri', ylabel='Süre (s)', title=label,
                    fontsize_label=11, fontsize_title=11)
    fig.suptitle('Veri Miktarı vs Sorgu Süreleri (Trend Çizgisiyle)',
                 fontsize=14, fontweight='bold')
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    fig.savefig(output_dir / '10_veri_vs_sorgu_scatter.svg', format='svg'); plt.close(fig)
    print(f"  [SVG] 10_veri_vs_sorgu_scatter.svg")

    # ── 11: Artillery Sonuçları (4 panel) ──
    art_deneyler = [(s['kullanici_sayisi'], s['artillery'])
                    for s in tum_sonuclar if s.get('artillery')]
    if art_deneyler:
        art_k    = [a[0] for a in art_deneyler]
        art_ort  = [a[1]['yanit_ortalama_ms'] for a in art_deneyler]
        art_p95  = [a[1]['yanit_p95_ms'] for a in art_deneyler]
        art_min  = [a[1]['yanit_min_ms'] for a in art_deneyler]
        art_max  = [a[1]['yanit_max_ms'] for a in art_deneyler]
        art_tp   = [a[1]['istek_saniye'] for a in art_deneyler]
        art_ok   = [a[1]['basarili_2xx'] for a in art_deneyler]
        art_fail = [a[1]['basarisiz'] for a in art_deneyler]

        fig, axes = plt.subplots(2, 2, figsize=(16, 12))

        # Sol üst: Yanıt süreleri (min-max aralığı ile)
        ax = axes[0, 0]
        ax.plot(range(len(art_k)), art_ort, 'o-', color='black', linewidth=2, markersize=5, label='Ortalama')
        ax.plot(range(len(art_k)), art_p95, 's--', color='gray', linewidth=1.5, markersize=4, label='p95')
        ax.fill_between(range(len(art_k)), art_min, art_max, alpha=0.1, color='black', label='Min-Max')
        stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='Yanıt Süresi (ms)',
                    title='Artillery HTTP Yanıt Süreleri')
        ax.set_xticks(range(len(art_k)))
        ax.set_xticklabels([str(k) for k in art_k], rotation=45, fontsize=9)
        ax.legend(fontsize=10)

        # Sağ üst: Throughput
        ax = axes[0, 1]
        ax.bar(range(len(art_k)), art_tp, color='black', alpha=0.8)
        stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='İstek/Saniye',
                    title='Artillery HTTP Throughput')
        ax.set_xticks(range(len(art_k)))
        ax.set_xticklabels([str(k) for k in art_k], rotation=45, fontsize=9)

        # Sol alt: Başarılı vs Başarısız
        ax = axes[1, 0]
        x = np.arange(len(art_k))
        w = 0.35
        ax.bar(x - w/2, art_ok, w, label='Başarılı (2xx)', color='#4CAF50', alpha=0.85)
        ax.bar(x + w/2, art_fail, w, label='Başarısız', color='#F44336', alpha=0.85)
        stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='İstek Sayısı',
                    title='Başarılı vs Başarısız İstekler')
        ax.set_xticks(x)
        ax.set_xticklabels([str(k) for k in art_k], rotation=45, fontsize=9)
        ax.legend(fontsize=10)

        # Sağ alt: Başarı oranı (%)
        ax = axes[1, 1]
        basari_oran = [ok / max(ok + fail, 1) * 100 for ok, fail in zip(art_ok, art_fail)]
        ax.plot(range(len(art_k)), basari_oran, 'o-', color='#2196F3', linewidth=2, markersize=6)
        ax.axhline(y=100, color='green', linestyle='--', alpha=0.5, label='%100 hedef')
        stil_uygula(ax, xlabel='Kullanıcı Sayısı', ylabel='Başarı Oranı (%)',
                    title='HTTP Başarı Oranı')
        ax.set_xticks(range(len(art_k)))
        ax.set_xticklabels([str(k) for k in art_k], rotation=45, fontsize=9)
        ax.set_ylim(0, 105)
        ax.legend(fontsize=10)

        fig.tight_layout()
        fig.savefig(output_dir / '11_artillery_sonuclari.svg', format='svg'); plt.close(fig)
        print(f"  [SVG] 11_artillery_sonuclari.svg")

    print(f"\n  Tüm grafikler ve tablolar '{output_dir}' klasörüne kaydedildi.")


def main():
    deney_matrisi = deney_matris_olustur()
    deney_sayisi = len(deney_matrisi)

    print("=" * 70)
    print(f"  ASİS - PERFORMANS ANALİZ SCRİPTİ (Artillery + DB)")
    print(f"  {deney_sayisi} Deney | Kurum × Uzman matrisi | 6 Sorgu")
    print("=" * 70)

    print(f"\n[BİLGİ] Script dizini  : {SCRIPT_DIR}")
    print(f"[BİLGİ] Performans dir : {PERFORMANS_DIR}")
    print(f"[BİLGİ] Proje kökü     : {PROJECT_DIR}")
    print(f"[BİLGİ] Medya dizini   : {PERF_DATA_DIR}")
    print(f"[BİLGİ] Çıktı dizini   : {OUTPUT_DIR}")
    print(f"[BİLGİ] Artillery hedef : {ARTILLERY_TARGET}")

    if PHOTO_SRC.exists():
        print(f"[OK] Fotoğraf bulundu: {PHOTO_SRC}")
    else:
        print(f"[UYARI] Fotoğraf bulunamadı: {PHOTO_SRC}")

    if VIDEO_SRC.exists():
        print(f"[OK] Video bulundu  : {VIDEO_SRC}")
    else:
        print(f"[UYARI] Video bulunamadı: {VIDEO_SRC}")

    # Artillery helpers.js yolu
    helpers_path = SCRIPT_DIR / 'helpers.js'
    if not helpers_path.exists():
        print(f"[UYARI] Artillery helpers.js bulunamadı: {helpers_path}")

    # ── Artillery ön kontrol: Başlamadan önce bir kez kur ──
    artillery_hazir = False
    artillery_bin = artillery_binary_bul()
    if artillery_bin:
        print(f"[OK] Artillery bulundu: {artillery_bin}")
        artillery_hazir = True
    else:
        print(f"\n[BİLGİ] Artillery bulunamadı, otomatik kurulum deneniyor...")
        print(f"        Dizin: {SCRIPT_DIR}")
        if artillery_kur():
            artillery_bin = artillery_binary_bul()
            if artillery_bin:
                print(f"[OK] Artillery kuruldu: {artillery_bin}")
                artillery_hazir = True
            else:
                print(f"[UYARI] Artillery kurulumu tamamlandı ama binary bulunamadı.")
        else:
            print(f"[UYARI] Artillery kurulamadı. HTTP yük testleri atlanacak.")
            print(f"        Manuel kurulum: cd {SCRIPT_DIR} && npm install")

    # PostgreSQL sunucusuna bağlan
    admin_conn = admin_connect()
    print(f"\n[OK] PostgreSQL sunucu bağlantısı: {DB_CONFIG['host']}:{DB_CONFIG['port']}")

    # Deney matrisi oluştur
    print(f"\n[BİLGİ] {deney_sayisi} Deney planlandı (kurum × uzman):")
    print(f"         Kurum sayıları: {KURUM_SAYILARI}")
    print(f"         Uzman sayıları: {UZMAN_SAYILARI}")
    print(f"         Deney  1 → {deney_matrisi[0]['kurum_sayisi']} kurum × {deney_matrisi[0]['uzman_sayisi']} uzman = {deney_matrisi[0]['toplam_kullanici']:>5} kullanıcı")
    print(f"         Deney {deney_sayisi} → {deney_matrisi[-1]['kurum_sayisi']} kurum × {deney_matrisi[-1]['uzman_sayisi']} uzman = {deney_matrisi[-1]['toplam_kullanici']:>5} kullanıcı")
    tum_sonuclar = []

    print(f"\n{'Deney':>5} | {'DB Adı':<16} | {'Kurum':>5} | {'Uzman':>5} | {'Toplam':>7} | {'Veri':>10} | "
          f"{'Insert(s)':>10} | {'S1(s)':>8} | {'S2(s)':>8} | {'S3(s)':>8} | "
          f"{'S4(s)':>8} | {'S5(s)':>8} | {'S6(s)':>8} | {'Art.':>6}")
    print("-" * 160)

    # Geçici dizin: Artillery dosyaları için
    tmp_dir = Path(tempfile.mkdtemp(prefix='asis_artillery_'))

    for deney_idx in range(deney_sayisi):
        deney_no = deney_idx + 1
        deney_config = deney_matrisi[deney_idx]
        k_sayisi = deney_config['kurum_sayisi']
        u_sayisi = deney_config['uzman_sayisi']

        # 1) Veritabanı oluşturulması
        db_name = create_experiment_db(admin_conn, deney_no)

        # 2) Yeni veritabanına bağlanılması
        conn = connect_experiment_db(db_name)

        # 3) Şemanın kurulması
        setup_schema(conn)

        # 4) Olay türlerinin eklenmesi
        olay_turu_ids = olay_turlerini_ekle(conn)

        # 5) Kullanıcıların oluşturulması (yeni mantık: kurum × uzman)
        kullanicilar, kurum_map = kullanicilari_olustur(conn, deney_config)
        gercek_k_sayisi = len(kullanicilar)

        # 6) Verileri eklenmesi (doğrudan DB'ye – sorgu testi için)
        toplam_veri, insert_suresi = veri_ekle(conn, kullanicilar, olay_turu_ids)

        # 7) Sorguların çalışması (6 sorgu)
        sorgular = supervizor_sorgulari(conn, kurum_map)

        # 8) Bağlantıyı kapat
        conn.close()

        # 9) Artillery HTTP Yük Testi (sunucu çalışıyorsa ve artillery kuruluysa)
        artillery_sonuc = None
        if artillery_hazir:
            csv_path = tmp_dir / f'test_users_{deney_no}.csv'
            yaml_path = tmp_dir / f'artillery_{deney_no}.yml'
            json_path = tmp_dir / f'artillery_{deney_no}_result.json'

            artillery_csv_olustur(kullanicilar, csv_path)
            artillery_yaml_olustur(gercek_k_sayisi, str(csv_path), str(yaml_path), str(helpers_path))
            artillery_sonuc = artillery_calistir(str(yaml_path), str(json_path))

        sonuc = {
            'deney_no': deney_no,
            'db_adi': db_name,
            'kurum_sayisi': k_sayisi,
            'uzman_sayisi': u_sayisi,
            'kullanici_sayisi': gercek_k_sayisi,
            'toplam_veri': toplam_veri,
            'insert_suresi': round(insert_suresi, 3),
            'sorgular': sorgular,
            'artillery': artillery_sonuc,
        }
        tum_sonuclar.append(sonuc)

        s1 = sorgular['sorgu1_kurum']['sure_sn']
        s2 = sorgular['sorgu2_uzman']['sure_sn']
        s3 = sorgular['sorgu3_olay_turu']['sure_sn']
        s4 = sorgular['sorgu4_medya']['sure_sn']
        s5 = sorgular['sorgu5_tarih_kurum']['sure_sn']
        s6 = sorgular['sorgu6_tarih_kurum_count']['sure_sn']
        if artillery_sonuc:
            a = artillery_sonuc
            art_str = f"{a['yanit_ortalama_ms']:.1f}ms {a['basarili_2xx']}/{a['toplam_istek']}"
        else:
            art_str = "–"
        print(f"{deney_no:>5} | {db_name:<16} | {k_sayisi:>5} | {u_sayisi:>5} | "
              f"{gercek_k_sayisi:>7,} | {toplam_veri:>10,} | {insert_suresi:>10.3f} | "
              f"{s1:>8.4f} | {s2:>8.4f} | {s3:>8.4f} | {s4:>8.4f} | "
              f"{s5:>8.4f} | {s6:>8.4f} | {art_str:>6}")

    admin_conn.close()

    # Geçici dosyaları temizle
    shutil.rmtree(tmp_dir, ignore_errors=True)

    print(f"\n[4/4] Grafikler ve tablolar oluşturuluyor...")
    grafik_olustur(tum_sonuclar, OUTPUT_DIR)

    json_path = OUTPUT_DIR / 'deney_sonuclari.json'
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(tum_sonuclar, f, ensure_ascii=False, indent=2)
    print(f"  [JSON] {json_path}")

    print(f"\n{'=' * 70}")
    print(f"  TAMAMLANDI!")
    print(f"  pgAdmin'de {deney_sayisi} veritabanı görünür:")
    print(f"    asis_deney_1, ..., asis_deney_{deney_sayisi}")
    print(f"  Grafikler: {OUTPUT_DIR}")
    print(f"{'=' * 70}")


if __name__ == '__main__':
    main()